### ISSUE TITLE
Unhandled errors and wrong types in the context

### ISSUE THREAD

**Issue by alireza-ahmadi** [huv1k/nextjs-auth-prisma#29]
With the current implementation, the demo server (and also any attempt for running this locally) returns `An unexpected error has occurred.`.

I did a quick investigation and found out that this error is a result of a combination of issues on both the client and server.

### Error Handling

https://github.com/huv1k/nextjs-auth-prisma/blob/bf655295ce951b723fc4d0e9e94a69540c5c37b3/src/pages/index.tsx#L9

Here, we are ignoring the `error` object, therefore there can be cases where `fetching === false` and `data` is not an empty object, but `data` is not the object that it should be; As a result, React would try to render the `Viewer` component and would raise an unhandled exception because `data.viewer` is `null`.

To solve this issue, we can choose a more defensive approach and make sure that `error` is empty and `data.viewer` isn't `null`.

### Auth (server-side)

If the user is not authenticated, the `token` variable in the line below would be `null`:

https://github.com/huv1k/nextjs-auth-prisma/blob/bf655295ce951b723fc4d0e9e94a69540c5c37b3/src/lib/nexus/context.ts#L43

The problem is `viewer` resolver (_code below_), assumes that `id` is always present; Therefore, the resolver tries to invoke `findUnique` method with the `id` variable from context, which would be `undefined` for unauthenticated users. In absence of the `id`, the server returns an error to the client, expressing the condition that passed to the `findUnique` method is wrong.

https://github.com/huv1k/nextjs-auth-prisma/blob/bf655295ce951b723fc4d0e9e94a69540c5c37b3/src/lib/nexus/types/user.ts#L16-L21

A better implementation would be, again, choosing a more defensive approach and informing the client that an unauthenticated user cannot request for viewer's info, by raising a custom error.

---

I'd be glad if you comment on the mentioned problems. Also, I'm not aware of your plans for this boilerplate but, if you think that these problems should be fixed, I'd be happy to send a PR.

And BTW, thanks for the boilerplate.

**Comment by huv1k** [comment]
Hey @alireza-ahmadi,
thanks for the thorough feedback! Sorry for the late response, I was a little bit busy lately. 

### Error Handling
Yes, we should choose a more defensive approach, which you proposing to make more sense. I just took a shortcut for the first iteration. There should be handling for `null`.

### Auth (server-side)
Yes, like you mention it's the wrong implementation, I wanted to go again with a short path and ignore handling these states. It makes 100% sense to have this in the production-ready application. This boilerplate was made from my side project and I want to keep it updated! We should have `id` as optional param and properly handle this state in resolvers.

If you have free time please contribute! I would like to keep it up to date, but it's hard to keep with all of my stuff going on right now.

**Comment by alireza-ahmadi** [comment]
Hey @huv1k,
Thanks for the response.

I understand that this is a boilerplate hence, there is no need for handling every single state.

However, IMHO, the online demo and first attempt for running the boilerplate are somehow the first impressions of a developer from working with this codebase and, facing an unhandled exception right off the bat can prevent them from trusting this boilerplate, even though code quality and structure is great. So, while I explained the issue in detail to clarify it, my suggestion is to make the demo work without implementing a complex error handling solution or trying to handle every single state.

I will take a look at the codebase and, if time lets me, will send a PR in the next few days.
