### ISSUE TITLE
Move to the new Codegen client preset

### ISSUE THREAD

**Issue by Urigo** [huv1k/nextjs-auth-prisma#487]
We released the new Codegen client preset which is now the recommended way to use Codegen on the frontend.
We would love to support you upgrading to it and to learn from your feedback on it:
https://the-guild.dev/blog/unleash-the-power-of-fragments-with-graphql-codegen

**Comment by huv1k** [comment]
I already have this one https://github.com/huv1k/nextjs-auth-prisma/pull/200 🙌 didn't push it over the finish line yet. Maybe this week 🙌
